name: Deploy to ECS on Fargate
on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ROLE: ${{secrets.AWS_PREFIX}}:role/github_actions

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE }}
          role-session-name: github-ecr
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPO: 
          IMAGE_TAG: ${{ github.sha }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true



